### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Dre-Tas** [specklesystems/xUnitRevit#1]
Hey guys! Thanks for the effort. Really appreciated!!

I am looking forward to use this project to test my app, but so far I am failing at building it for Revit 2020 (or any other version).
I'm following the instructions in the readme, but I'm always getting this error and I'm not too sure what it means / what to do about it:
![image](https://user-images.githubusercontent.com/36023527/92567972-d1c24080-f2c1-11ea-871c-1172f870af11.png)

I cloned the project, I selected Debug2020 as the mode and when I hit Start or Build I get this error. I get the same error is I use the Release mode.

What am I doing wrong?

Cheers

**Comment by teocomi** [comment]
Sounds like VS being a bit iffy... Have you tried rebuilding the whole solution? Do you have .net standard installed / what version of VS are you using?

**Comment by Dre-Tas** [comment]
Yeah I tried the entire solution > same error.
I'm using VS2019, but now that you say it, I'm actually not sure if I have .net standard 😬 which version would I need?

**Comment by Dre-Tas** [comment]
Ah yeah the error says it. 2.0 right?
I'll try now and let you know

**Comment by Dre-Tas** [comment]
Different error this time:
![image](https://user-images.githubusercontent.com/36023527/92572716-236dc980-f2c8-11ea-88f5-3fde59f424ed.png)

**Comment by izzylys** [comment]
hey Andrea! 

in order to run, you'll need to make your own `config.json` inside the `xUnitRevit` directory. there's a `config_sample.json` in there for a template. you can add a path to the .dll of the tests you want to auto-load (or leave it blank if you don't mind loading it up yourself) and set `autoStart` which toggles whether or not the app will launch on Revit startup

**Comment by Dre-Tas** [comment]
Thanks @izzylys !! That fixed it 🥳 
You actually need to have both the config.json and config_sample.json I found out. I renamed config_sample to config and VS complained that it wanted both...

I'm thinking of making a PR specifying this step in the Getting started instructions (in the readme) as I think it might help future users. Would this be useful?

**Comment by izzylys** [comment]
Perfect, glad to hear you got it working @Dre-Tas 🎉 I don't think that's the intended behaviour, so thanks for pointing that out. 

I agree re the docs – it's mentioned in the additional notes section, but would make more sense in the actual getting started steps. People tend to skim these things, so better make it more obvious 😉 Feel free to make a PR if you're so inclined!

happy testing 🛠️

**Comment by teocomi** [comment]
I think the problem is that I've untracked those files from git but they're still part of the VS project... 
Maybe we can just remove config.json from the project or add an empty one.
