### ISSUE TITLE
Update .gitmodules to use https url instead of ssh

### ISSUE THREAD

**Issue by JamesDrummond** [specklesystems/xUnitRevit#29]
Can you change url of .gitmodules from `git@github.com:specklesystems/speckle.xunit.runner.wpf.git` to `https://github.com/specklesystems/xUnitRevit.git`? I got authentication issues trying to clone the repo using Github Desktop. I am sure I could figure out how to create and use a ssh public key but others will probably have similar issues trying to clone repo. Below is what the .gitmodules would change to.

Current
```
[submodule "speckle.xunit.runner.wpf"]
	path = speckle.xunit.runner.wpf
	url = git@github.com:specklesystems/speckle.xunit.runner.wpf.git
```

Suggested
```
[submodule "speckle.xunit.runner.wpf"]
	path = speckle.xunit.runner.wpf
	url = https://github.com/specklesystems/xUnitRevit.git
```

**Comment by teocomi** [comment]
Thanks for the report :) I found another solution that should be more universal, let me know if it works for you https://github.com/specklesystems/xUnitRevit/commit/fba1d1ce323b8326194f52480287d3a738ea7d3c

**Comment by JamesDrummond** [comment]
That works. Thanks.
