### ISSUE TITLE
config file in your xUnitRevit project is missing

### ISSUE THREAD

**Issue by dfgind** [specklesystems/xUnitRevit#30]
Hello Matteo,

I was trying out your tool but the config file in your xUnitRevit project is missing. Do you have a back up?

[Page not found · GitHub](https://github.com/specklesystems/xUnitRevit/blob/master/xUnitRevitRunner/config_sample.json)

Diego

**Comment by connorivy** [comment]
Hi @dfgind,

We recently did some reorganization in our project, and you probably found a link that we haven't updated yet. You can find the file here
https://github.com/specklesystems/xUnitRevit/blob/master/xUnitRevitRunner/xUnitRevitRunnerShared/config_sample.json

**Comment by dfgind** [comment]
just found it and followed the steps and it worked. 
Thanks a lot @connorivy
