### ISSUE TITLE
Revit crashing when reading assembly in modeless dialog (Revit 2020)

### ISSUE THREAD

**Issue by LotharTUM** [specklesystems/xUnitRevit#7]
Dear xUnitRevit-Team,
first of all thank you very much for your great work, i appreciate a lot!
Unfortunately i encountered an issue when configuring xUnitRevit for Revit 2020: The modeless dialog makes Revit crashes when i read in the .dll of the modeless dialog. Revit crashes without any usable error message... 

I used the sampleLibrary and exchanged the TestModel to a Revit-2020 model that has four walls and two slabs.
I created the .dll having installed the NuGet-Packages for xUnit and xUnitRevitUtils2020.

Would anyone have an advise for me? Also a more minimalist test sample i would appreciate, to ensure that the workflow in general works.

Thank you very much!
Kind Regards

**Comment by teocomi** [comment]
Hi @LotharTUM ,

Let's try to see what's going on! 

- Does xUnitRevit for Revit 2020 open up correctly in Revit 2020?
- If you create a simple class library with a couple of xUnit tests **and no reference to the Revit api**, does it open and run fine inside xUnitRevit?

**Comment by LotharTUM** [comment]
Hello Teocomi,
thank you for your fast response! Both of your hints were okay in my project (the GUI was showing up and i could run unit tests without revit API reference). 

To ensure i had not done any configuring error i set up the project again and now it worked. I think i had either an error in the target framework property of the test library or built the projects inconsistently (one as debug, the other as release).

Thank you!
Regards
Lothar
