### ISSUE TITLE
Unable to perform transaction in test

### ISSUE THREAD

**Issue by LotharTUM** [specklesystems/xUnitRevit#8]
Hello dear xUnitRevit-Team,
i get an exception when trying to run a test that uses the temporary transaction trick (https://thebuildingcoder.typepad.com/blog/2012/10/the-temporary-transaction-trick-for-gross-slab-data.html). The Revit API then (of course) complains that the model must not be manipulated from outside. 

Did somebody find a solution to deviate this problem? Might there be a possibility with xru.RunInTransaction?
Thanks a lot!

**Comment by teocomi** [comment]
@LotharTUM thanks for reporting this! 
Do you have a snippet of code to reproduce the issue?

**Comment by LotharTUM** [comment]
Hello Matteo!
The function i want to test is this: 

> static public PlanarGeometry GetWallContour(Wall wall, Document doc)
> {
>             IList<ElementId> inserts = wall.FindInserts(true, true, true, true);
>             Transaction temporaryTransaction = new Transaction(doc);
>             temporaryTransaction.Start("Temporary - only to get gross area");
>             foreach (ElementId insertId in inserts) {doc.Delete(insertId);}
>             doc.Regenerate(); 
>             IList<Reference> wallFaceReference = HostObjectUtils.GetSideFaces(wall, ShellLayerType.Exterior);
>             PlanarFace face = doc.GetElement(wallFaceReference.First())
>                        .GetGeometryObjectFromReference(wallFaceReference.First()) as PlanarFace;
>             IList<CurveLoop> wallFaceEdges = face.GetEdgesAsCurveLoops();      
>             double grossArea = ExporterIFCUtils.ComputeAreaOfCurveLoops(wallFaceEdges);
>             PlanarGeometry wallGeometry = new PlanarGeometry(wallFaceEdges.First(), face.FaceNormal, grossArea);
>             temporaryTransaction.RollBack();
>             return wallGeometry;
> }

Thanks a lot!

**Comment by teocomi** [comment]
Hey @LotharTUM , thanks for the additional info and feedback!
I've added a `xru.Run()` method that will allow you to have more control over the transaction, you can see the updated example:
https://github.com/specklesystems/xUnitRevit/blob/master/SampleLibrary/SampleTest.cs#L42-L70

**Comment by LotharTUM** [comment]
Thanks Matteo!
